put: Specified block size is less than configured minimum value (dfs.namenode.fs-limits.min-block-size): 8192 < 1048576
file 3 has been put into HDFS
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
2019-03-25 19:41:44,245 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1023ms.
2019-03-25 19:41:45,276 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2359ms.
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
rm: `/myfile3': No such file or directory
file 3 has been removed from HDFS
put: Specified block size is less than configured minimum value (dfs.namenode.fs-limits.min-block-size): 8192 < 1048576
file 3 has been put into HDFS
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
2019-03-25 19:42:10,918 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 886ms.
2019-03-25 19:42:11,811 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1510ms.
2019-03-25 19:42:13,323 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2065ms.
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
rm: `/myfile3': No such file or directory
file 3 has been removed from HDFS
put: Specified block size is less than configured minimum value (dfs.namenode.fs-limits.min-block-size): 8192 < 1048576
file 3 has been put into HDFS
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
2019-03-25 19:43:02,074 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 547ms.
2019-03-25 19:43:02,628 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2387ms.
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
2019-03-25 19:43:25,937 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1155ms.
2019-03-25 19:43:27,099 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1732ms.
2019-03-25 19:43:28,834 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3717ms.
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
rm: `/myfile3': No such file or directory
file 3 has been removed from HDFS
put: Specified block size is less than configured minimum value (dfs.namenode.fs-limits.min-block-size): 8192 < 1048576
file 3 has been put into HDFS
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
get: `/myfile3': No such file or directory
TEST_ERROR: get failed!
file 3 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile3: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile3': No such file or directory
