Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile5
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
file 2 has been read from HDFS for 4 time
diff succeed!
file 2 has been read from HDFS for 5 time
diff succeed!
file 2 has been read from HDFS for 6 time
diff succeed!
file 2 has been read from HDFS for 7 time
diff succeed!
file 2 has been read from HDFS for 8 time
diff succeed!
file 2 has been read from HDFS for 9 time
diff succeed!
file 2 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile2
file 2 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:25 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile3
-rw-r--r--   3 root supergroup  536870912 2019-03-20 11:25 /myfile4._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:23 /myfile5
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
file 2 has been read from HDFS for 4 time
diff succeed!
file 2 has been read from HDFS for 5 time
diff succeed!
file 2 has been read from HDFS for 6 time
diff succeed!
file 2 has been read from HDFS for 7 time
diff succeed!
file 2 has been read from HDFS for 8 time
diff succeed!
file 2 has been read from HDFS for 9 time
diff succeed!
file 2 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile2
file 2 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:26 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:27 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:26 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:25 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:26 /myfile5
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
file 2 has been read from HDFS for 4 time
diff succeed!
file 2 has been read from HDFS for 5 time
diff succeed!
file 2 has been read from HDFS for 6 time
diff succeed!
file 2 has been read from HDFS for 7 time
diff succeed!
file 2 has been read from HDFS for 8 time
diff succeed!
file 2 has been read from HDFS for 9 time
diff succeed!
file 2 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile2
file 2 has been removed from HDFS
2019-03-20 11:29:10,726 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 951ms.
2019-03-20 11:29:11,685 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2560ms.
2019-03-20 11:29:14,248 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3174ms.
Found 3 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:29 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:27 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-20 11:28 /myfile5
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
2019-03-20 11:30:10,167 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.io.EOFException: End of File Exception between local host is: "clnode051.clemson.cloudlab.us/130.127.133.60"; destination host is: "node-1-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1440ms.
2019-03-20 11:30:11,614 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2872ms.
2019-03-20 11:30:14,489 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5235ms.
2019-03-20 11:30:19,729 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10251ms.
2019-03-20 11:30:29,982 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12636ms.
2019-03-20 11:30:42,620 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13569ms.
2019-03-20 11:30:56,191 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22178ms.
2019-03-20 11:31:18,372 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode051.clemson.cloudlab.us/130.127.133.60 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7664ms.
